"""empty message

Revision ID: 05c85fb15874
Revises: bce5695e9954
Create Date: 2022-01-07 19:30:56.367282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c85fb15874'
down_revision = 'bce5695e9954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people', 'user', ['user_id'], ['id'])
    op.add_column('planets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planets', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='foreignkey')
    op.drop_column('planets', 'user_id')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'user_id')
    # ### end Alembic commands ###
